### ISSUE TITLE
PimpMyLogs to show logs per site

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#1]
Currently only displays the main apache logs but other log files exist for each site - can it display all apache logs?

**Comment by ghost** [comment]
support for ngnix and php is patchy at present, is there a better tool?

**Comment by ghost** [comment]
Had a look at this - problems to solve:
1. Apache should just have a single access and error log like nginx, no need for one per site as this clutters the pimpmylogs interface and we are unlikely to be developing multiple sites concurrently on our own boxes
2. pimpmylogs is installed via a git checkout to the mounted persistent storage directory which causes problems when trying to use chef to manage the config file for the same permission based issues that happened when trying to create ssl certificates - needs to be installed somewhere else
3. pimpmylogs version isn't updated by the chef script so versions differ between users boxes

**Comment by ghost** [comment]
last commit automatically sets up http://pimpmylogs.dev with all the right permissions.
