### ISSUE TITLE
Commandline utility

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#10]
What would make VDD really awesome is some kind of vdd cli...
(Symfony based of course)

So:

```
$cd ~/Sites/some-project
$vdd install
Project shortname? [some-project]
Path to docroot? [docroot]
Import a DB? #Paste a DB backup path here. .gz files are decompressed automatically.
Re-provision machine now? [yes]
Done! Visit your new site: http://some-project.dev
And off it goes... backup and update config.json then re-run vagrant --provision.
```

How cool would that be?! Steps to set up a site go down to just:

git clone
vdd install, enter, enter, cmd+v, enter
click link

**Comment by ghost** [comment]
Think we'll leave this now - the future of local development isn't vdd
