### ISSUE TITLE
turn off PHP short tags

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#12]
They are banned by Drupal coding standards and masked a bug that Adam and Steve were having the other day.

**Comment by angry-dan** [comment]
I don't think this is a problem if we move to 5.6?
I think 5.6 says something like <?= ?> is fine and <? ?> is never allowed?

Which feels right to me. Nobody likes typing <?php print $thing ;?>. <?= $thing ?> is much better.

Interestingly, Acquia allows short tags.

**Comment by ghost** [comment]
Think this is no longer a problem then
