### ISSUE TITLE
Tidy up the custom rb files

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#14]
Currently noticing the following things:
1. Unnecessary vdd_ name spacing
2. nginx.rb also deals with ssl - should be a separate ssl.rb recipe
3. vdd_sites could be separated in databases and sites
4. apache config templates are in the root of the templates dir and in the apache2 subfolder - move all into apache2 sub folder

**Comment by ghost** [comment]
Last commit fixes these.
