### ISSUE TITLE
Site installs fails due to private dir not writeable

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/vdd#15]
When running 'drush @vdd si' for a new site, it fails with the following error:

WD php: Exception: File system: Writable (public download method)                                                                                                           [error]

The directory /mnt/persistant/site-files/[SHORT_NAME]/private is not writable. An automated attempt to create this directory failed, possibly due to a permissions problem.
To proceed with the installation, either create the directory and modify its permissions manually or ensure that the installer has the permissions to create it
automatically. For more information, see INSTALL.txt or the online handbook. in install_verify_requirements() (line 773 of
/var/www/vhosts/shepsms.dev/docroot/includes/install.core.inc).
Cannot modify header information - headers already sent by (output started at /usr/local/bin/drush-master/includes/output.inc:38) bootstrap.inc:1232                      [warning]
Exception: File system: Writable (<em>public</em> download method)

The directory <em>/mnt/persistant/site-files/[SHORT_NAME]/private</em> is not writable. An automated attempt to create this directory failed, possibly due to a permissions problem. To proceed with the installation, either create the directory and modify its permissions manually or ensure that the installer has the permissions to create it automatically. For more information, see INSTALL.txt or the <a href="http://drupal.org/server-permissions">online handbook</a>. in install_verify_requirements() (line 773 of /var/www/vhosts/[SHORT_NAME].dev/docroot/includes/install.core.inc).

Commenting out the following line in the vdd settings enables this to work:

$conf['file_private_path'] = '/mnt/persistant/site-files/[SHORT_NAME]/private';

**Comment by ghost** [comment]
Thanks Mike, I've had this before as well. Will check permissions on the private files dirs.

**Comment by ghost** [comment]
drush from the cli is executed as the vagrant user. The private files dir is owned and group owned by www-data. 

I've added a chef thing to add vagrant user to the www-data group which seems to fix this
