### ISSUE TITLE
Add optional ability to install drupal into a subfolder

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#17]
It is occasionally required to have Drupal in a subfolder with other resources / scripts in the true site docroot.

i.e. assuming _myproject_ ....

_Project root_ ~/Sites/myproject.dev
_Web docroot_ ~/Sites/myproject.dev/docroot
_Drupal docroot_ ~/Sites/myproject.dev/docroot/drupal

Suggesting the following optional _drupal_sub_folder_ line for the site in config.json. Omitting this option assumes the docroot is at the _document_root_ as is currently the case.

```
  "myproject": {
    "account_name": "root",
    "account_pass": "root",
    "account_mail": "box@example.com",
    "site_name": "myproject.dev",
    "site_mail": "box@example.com",
    "type": "drupal7",
    "vhost": {
      "document_root" : "myproject.dev/docroot",
      "drupal_sub_folder" : "drupal",
      "url": "myproject.dev",
      "alias": ["www.myproject.dev"]
    }
  }
```

**Comment by ghost** [comment]
Still need to provide code for apache config and D6/D8 template updates

**Comment by ghost** [comment]
this is already in there
