### ISSUE TITLE
New version (Ubuntu Xenial and PHP 7)

### ISSUE THREAD

**Issue by BrianWillows** [teamdeeson/vdd#32]
http://php.net/supported-versions.php
This configuration is still using PHP 5.5. 
5.5 is coming to the end of life and we should be moving to 5.6. I'd really appreciate guidance on how to update this Vagrant configuration to use PHP 5.6 and Java 1.8
Also I got caught by the recent varnish update. Where should I be looking to have found this announcement? It took too long to solve.
Thanks
Brian Willows (visited you last Summer)

**Comment by ghost** [comment]
There is a new branch in development (xenial) which will use the latest stable Ubuntu and PHP 7. It's going to be cut down from the previous version to make it faster and easier to use so will be missing some of the bulky tools like varnish.

Update instructions will follow but we're looking at something by end of the month.

**Comment by ghost** [comment]
The new version is now road tested - update instructions are in the README.md file

https://github.com/teamdeeson/vdd
