### ISSUE TITLE
Tidy up config.json

### ISSUE THREAD

**Issue by johnennewdeeson** [teamdeeson/vdd#9]
Its got things in it per site that are never used...

```
"account_name": "root",
"account_pass": "root",
"account_mail": "box@example.com",
"site_mail": "box@example.com",
```

To go a bit further, I wondered if perhaps we should scrap the config.json route of adding sites to VDD at all. Since we have defined the directory projects are stored in (default is ~/Sites) we could just recurse over the folders in that dir and look for ones called [shortname].dev, making a site for each. Specific config could reside in an optional .vdd/config.json file in the project root meaning checking out the project code into ~/Sites and a reprovision would be enough to add it.

**Comment by ghost** [comment]
Tidying up the config.json happened in the xenial branch already.

Looking for sites in the Sites directory is presently out of scope as we want to approach this in a different way (containers)
